name: Deployment - Drift Detection

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
      AZURE_CLIENT_SECRET:
      AZURE_SUBSCRIPTION_ID:
      AZURE_TENANT_ID:

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch To Run Workflow - Leave Empty For Current Branch"
        required: false
        type: string

  schedule:
    - cron: "0 3 * * *"

jobs:
  Drift-Detection:
    runs-on: ubuntu-latest
    env:
      TF_LOG: "ERROR"
      INPUT_BRANCH: ${{ inputs.branch }}
      DISPATCH_BRANCH: ${{ github.event.inputs.branch }}

    outputs:
      env_name: ${{ steps.detect-env.outputs.env }}
      drift_status: ${{ steps.drift-plan.outputs.drift_status }}
      drift_exit_code: ${{ steps.drift-plan.outputs.exit_code }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Determine Branch & Environment
      - name: Determine Branch & Enviroment
        id: detect-env
        shell: bash
        run: |
          echo "Event: $GITHUB_EVENT_NAME"

           if [ "$GITHUB_EVENT_NAME" = "workflow_call" ]; then
            BRANCH="$INPUT_BRANCH"

           elif [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] && [ -n "$DISPATCH_BRANCH" ]; then
            BRANCH="$DISPATCH_BRANCH"

          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            BRANCH="$GITHUB_BASE_REF"

          else
            BRANCH="${GITHUB_REF#refs/heads/}"
          fi

          echo "Branch: $BRANCH"

          case "$BRANCH" in
            dev) ENV="dev" ;;
            staging) ENV="staging" ;;
            main) ENV="production" ;;
            *) echo "Invalid Branch: $BRANCH"; exit 1 ;;
            esac

          TFVARS_FILE="environments/${ENV}/backend.tfvars"

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
          echo "env=$ENV" >> $GITHUB_OUTPUT

          echo "Environment: $ENV"
          echo "Using TFVARS File: $TFVARS_FILE"

        # Terraform Backend Folders & Files
      - name: Terraform Backend Folders & Files
        run: |
          echo "Terraform Backend Folders & Files:"
          for dir in environments/terraform-backend/*; do
            if [ -d "$dir" ]; then
              echo "Folder: $dir"
              ls -1 "$dir"
            fi
          done

      # Determine Backend Variables
      - name: Determine Backend Variables
        run: |
          BACKEND_FILE="${TFVARS_FILE}"

          if [ ! -f "$BACKEND_FILE" ]; then
           echo "Backend TFVARS File Not Found: $BACKEND_FILE"
           exit 1
          fi

           RG=$(grep -E '^state_resource_group_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           SA=$(grep -E '^state_storage_account_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           CONTAINER=$(grep -E '^state_storage_container_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           KEY=$(grep -E '^state_key_deployment' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)

           RG="${RG//$'\r'/}"
           SA="${SA//$'\r'/}"
           CONTAINER="${CONTAINER//$'\r'/}"
           KEY="${KEY//$'\r'/}"

           echo "RG_NAME=$RG" >> $GITHUB_ENV
           echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
           echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
           echo "STATE_KEY_DEPLOYMENT=$KEY" >> $GITHUB_ENV

        # Clear Cahce
      - name: Clear Cache
        run: |
          echo "Cleaning Cache..."

          rm -rf .terraform .terraform.lock.hcl

          rm -rf environments/${ENV}/.terraform
          rm -f environments/${ENV}/.terraform.lock.hcl

          echo "Cleanup Complete"

        # Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

        # Terraform Version
      - name: Terraform Version
        working-directory: environments\terraform-backend\backend-migration
        run: terraform version

        # Initialize Terraform Withs Backend
      - name: Initialize Terraform
        working-directory: environments\terraform-backend\backend-migration
        run: |
          echo "Initializing Terraform Backend..."
          terraform init \
          -backend-config="resource_group_name=$RG_NAME" \
          -backend-config="storage_account_name=$STORAGE_ACCOUNT_NAME" \
          -backend-config="container_name=$STORAGE_CONTAINER_NAME" \
          -backend-config="key=$STATE_KEY_DEPLOYMENT"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      # Terraform Plan - Drift Detection
      - name: Terraform Drift Detection
        id: drift-plan
        run: |
          echo "Running Terraform Drift Detection..."
          terraform plan \
          -var-file="$TFVARS_FILE" \
          -detailed-exitcode \
          -out=tfplan
          exit_code=$?

          echo "Terraform exit code: $exit_code"
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT

          if [ $exit_code -eq 0 ]; then
            echo "Drift Status: No Changes Detected"
            echo "drift_status=no_drift" >> $GITHUB_OUTPUT

          elif [ $exit_code -eq 2 ]; then
            echo "Drift Status: Drift Detected! Current Code & Deployed Infra Mismatch"
            echo "drift_status=drift_detected" >> $GITHUB_OUTPUT

          else
            echo "Terraform plan failed"
            echo "drift_status=error" >> $GITHUB_OUTPUT
            exit 1
          fi
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
