name: Pipeline Orchestrator

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch To Deploy ( dev | staging | main )"
        required: true
        type: string

permissions:
  contents: read

jobs:
  # Terraform Format
  terraform-format:
    name: Terraform
    uses: ./.github/workflows/terraform-format.yml
    with:
      branch: ${{ inputs.branch }}

  # Terraform Validate
  terraform-validate:
    name: Terraform
    uses: ./.github/workflows/terraform-validate.yml
    with:
      branch: ${{ inputs.branch }}

  # Terraform Linting
  terraform-linting:
    name: Terraform
    needs:
      - terraform-format
      - terraform-validate
    uses: ./.github/workflows/terraform-linting.yml
    with:
      branch: ${{ inputs.branch }}

  # Security - Checkov
  Security-Checkov:
    name: Security
    needs: terraform-linting
    uses: ./.github/workflows/security-checkov.yml
    with:
      branch: ${{ inputs.branch }}

  # Security - Trivy IAC
  Security-Trivy-IAC:
    name: Security
    needs: terraform-linting
    uses: ./.github/workflows/security-trivy-iac.yml
    with:
      branch: ${{ inputs.branch }}

  # Security - Trivy Secrets
  Security-Trivy-Secrets:
    name: Security
    needs: terraform-linting
    uses: ./.github/workflows/security-trivy-secrets.yml
    with:
      branch: ${{ inputs.branch }}

  # Terraform Plan
  terraform-plan:
    name: Terraform
    needs:
      - Security-Checkov
      - Security-Trivy-IAC
      - Security-Trivy-Secrets
    uses: ./.github/workflows/terraform-validate.yml
    with:
      branch: ${{ inputs.branch }}
