name: Security - Trivy IAC

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch To Run Workflow - Leave Empty To Use Current Branch"
        required: false
        type: string

  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  Trivy-IAC:
    runs-on: ubuntu-latest
    env:
      TF_LOG: "ERROR"
      INPUT_BRANCH: ${{ inputs.branch }}
      DISPATCH_BRANCH: ${{ github.event.inputs.branch }}

    outputs:
      env_name: ${{ steps.detect-env.outputs.env }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Terraform Version
      - name: Terraform Version
        working-directory: .
        run: terraform version

      # Determine Branch & Environment
      - name: Determine Branch & Enviroment
        id: detect-env
        shell: bash
        run: |
          echo "Event: $GITHUB_EVENT_NAME"

           if [ "$GITHUB_EVENT_NAME" = "workflow_call" ]; then
            BRANCH="$INPUT_BRANCH"

           elif [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] && [ -n "$DISPATCH_BRANCH" ]; then
            BRANCH="$DISPATCH_BRANCH"

          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            BRANCH="$GITHUB_BASE_REF"

          else
            BRANCH="${GITHUB_REF#refs/heads/}"
          fi

          echo "Branch: $BRANCH"

          case "$BRANCH" in
            dev) ENV="dev" ;;
            staging) ENV="staging" ;;
            main) ENV="production" ;;
            *) echo "Invalid Branch: $BRANCH"; exit 1 ;;
            esac

          TFVARS_FILE="environments/${ENV}/${ENV}.tfvars"

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
          echo "env=$ENV" >> $GITHUB_OUTPUT

          echo "Environment: $ENV"
          echo "Using TFVARS File: $TFVARS_FILE"

        # Modules
      - name: List Module Folders
        run: ls -l modules/

        # Trivy Scan
      - name: Trivy IAC Scan - Root Infra
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: config
          scan-ref: .
          tf-vars: ${{ env.TFVARS_FILE }}
          skip-dirs: environments/terraform-backend
          format: table
          hide-progress: false
          severity: CRITICAL,HIGH
          exit-code: "1"
