name: Security - Checkov

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch To Run Workflow - Leave Empty To Use Current Branch"
        required: false
        type: string

  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  checkov:
    runs-on: ubuntu-latest
    env:
      TF_LOG: "ERROR"
      INPUT_BRANCH: ${{ inputs.branch }}
      DISPATCH_BRANCH: ${{ github.event.inputs.branch }}

    outputs:
      env_name: ${{ steps.detect-env.outputs.env }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      # Terraform Version
      - name: Terraform Version
        working-directory: .
        run: terraform version

      # Determine Branch & Environment
      - name: Determine Branch & Enviroment
        id: detect-env
        shell: bash
        run: |
          echo "Event: $GITHUB_EVENT_NAME"

           if [ "$GITHUB_EVENT_NAME" = "workflow_call" ]; then
            BRANCH="$INPUT_BRANCH"

           elif [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] && [ -n "$DISPATCH_BRANCH" ]; then
            BRANCH="$DISPATCH_BRANCH"

          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            BRANCH="$GITHUB_BASE_REF"

          else
            BRANCH="${GITHUB_REF#refs/heads/}"
          fi

          echo "Branch: $BRANCH"

          case "$BRANCH" in
            dev) ENV="dev" ;;
            staging) ENV="staging" ;;
            main) ENV="production" ;;
            *) echo "Invalid Branch: $BRANCH"; exit 1 ;;
            esac

          TFVARS_FILE="environments/${ENV}/${ENV}.tfvars"

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
          echo "env=$ENV" >> $GITHUB_OUTPUT

          echo "Environment: $ENV"
          echo "Using TFVARS File: $TFVARS_FILE"

        # Modules
      - name: List Module Folders
        run: ls -l modules/

        # Initialize Terraform Without Backend
      - name: Initialize Terraform
        working-directory: .
        run: terraform init -backend=false

        # Run Checkov
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          var_file: ${{ env.TFVARS_FILE }}
          framework: terraform
          check: CKV_AZURE_*
          soft_fail: false
          output_format: cli
          download_external_modules: true

          # HTTP (160) - KV Pure Protection (110) - CA Local Auth (236) - AKS SLA Paid SKU (170) - Min 50 Pods - AKS API Auth IP -CA Diabled Public Network (124) - SA Blob Public Access (190) - SA Public Access (59) - Queue Logging (33) - ACR Disabled Public Network (139) - ACR Dataend Point (237) - AKS Private CLuster (115) - Critical System Pods (232) - KV Recoverable (42) - App GW HTTPs (217) - App GW SSL (218) - SB DOuble Encrypt (199) - SB Public Network (204) - App GW WAF (120) - Search Identity, SA Replication (206)
          skip_check: CKV_AZURE_160,CKV_AZURE_110,CKV_AZURE_236,CKV_AZURE_170,CKV_AZURE_168,CKV_AZURE_6,CKV_AZURE_124,CKV_AZURE_190,CKV_AZURE_59,CKV_AZURE_33,CKV_AZURE_193,CKV_AZURE_237,CKV_AZURE_115,CKV_AZURE_232,CKV_AZURE_42,CKV_AZURE_217,CKV_AZURE_218,CKV_AZURE_199,CKV_AZURE_204,CKV_AZURE_120,CKV_AZURE_139,CKV_AZURE_207,CKV_AZURE_233,CKV_AZURE_206
