name: Terraform Static Analysis

on:
  workflow_dispatch:

  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  terraform-format-validate:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      TF_LOG: "ERROR"

    outputs:
      env_name: ${{ steps.detect-env.outputs.env }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Determine Branch
      - name: Determine Environment Based On Branch
        id: detect-env
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH="${{ github.base_ref }}"
          else
            BRANCH="${{ github.ref_name }}"
          fi

          case "$BRANCH" in
            dev) ENV="dev" ;;
            staging) ENV="staging" ;;
            main) ENV="production" ;;
            *) echo "Invalid branch: $BRANCH"; exit 1 ;;
            esac

          TFVARS_FILE="environments/${ENV}/${ENV}.tfvars"

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
          echo "env=$ENV" >> $GITHUB_OUTPUT

          echo "Environment: $ENV"
          echo "Using TFVARS File: $TFVARS_FILE"

        # Clear Cahce
      - name: Clear Cache
        run: |
          echo "Cleaning Cache..."

          rm -rf .terraform .terraform.lock.hcl

          rm -rf environments/${ENV}/.terraform
          rm -f environments/${ENV}/.terraform.lock.hcl

          echo "Cleanup Complete"

      - name: List Module Folders
        run: ls -l modules/

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

        # TF Version
      - name: Terraform Version
        working-directory: .
        run: terraform version

        # Format
      - name: Terraform FMT
        working-directory: .
        run: terraform fmt -check -recursive

        # Initialize Terraform Without Backend
      - name: Initialize Terraform
        working-directory: .
        run: terraform init -backend=false -var-file="$TFVARS_FILE"

        # Validation
      - name: Terraform Validate
        working-directory: .
        run: terraform validate

  tflint:
    name: TFLint
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: terraform-format-validate
    env:
      ENV: ${{ needs.terraform-format-validate.outputs.env_name }}
      TFVARS_FILE: environments/${{ needs.terraform-format-validate.outputs.env_name }}/${{ needs.terraform-format-validate.outputs.env_name }}.tfvars

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

        # Clear Cache
      - name: Clear Cache
        run: |
          echo "Cleaning Cache..."

          rm -rf .terraform .terraform.lock.hcl
          rm -rf ~/.tflint.d

          rm -rf environments/${ENV}/.terraform
          rm -f environments/${ENV}/.terraform.lock.hcl

          echo "Cleanup Complete."

        # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

        # Initialize Terraform Without Backend
      - name: Terraform Init
        working-directory: .
        run: terraform init -backend=false -var-file="$TFVARS_FILE"

        # Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

        # Azure TFLint config
      - name: Configure Azure TFLint Rules
        run: |
          cat <<EOF > .tflint.hcl
          config {
            format = "compact"
          }

          plugin "azurerm" {
            enabled = true
            source  = "github.com/terraform-linters/tflint-ruleset-azurerm"
            version = "0.27.0"
          }

          rule "terraform_unused_declarations" {
            enabled = true
            level   = "WARNING"
          }
          EOF

        # TF Init
      - name: Initialize TFLint
        working-directory: .
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Run RFLint
      - name: Run TFLint
        working-directory: .
        run: |
          echo "Running TFLint..."
          tflint --format compact --var-file="$TFVARS_FILE" || true

  checkov-security-analysis:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    name: Checkov Security Analysis
    runs-on: ubuntu-latest
    needs:
      - terraform-format-validate
      - tflint

    env:
      ENV: ${{ needs.terraform-format-validate.outputs.env_name }}
      TFVARS_FILE: environments/${{ needs.terraform-format-validate.outputs.env_name }}/${{ needs.terraform-format-validate.outputs.env_name }}.tfvars

    outputs:
      env_name: ${{ steps.set-env.outputs.env }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

        # Set Environment Output
      - name: Set Environment Output
        id: set-env
        run: |
          echo "Environment Detected: $ENV"
          echo "env=${ENV}" >> $GITHUB_OUTPUT

        # Clear Cache
      - name: Clear Cache
        run: |
          echo "Cleaning Cache..."

          rm -rf .terraform .terraform.lock.hcl
          rm -rf ~/.checkov

          rm -rf environments/${ENV}/.terraform
          rm -f environments/${ENV}/.terraform.lock.hcl

          echo "Cleanup Complete."

      #  Run Checkov
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          var_file: ${{ env.TFVARS_FILE }}
          framework: terraform
          check: CKV_AZURE_*
          soft_fail: false
          output_format: cli
          download_external_modules: true

          # HTTP (160) - KV Pure Protection (110) - CA Local Auth (236) - AKS SLA Paid SKU (170) - Min 50 Pods - AKS API Auth IP -CA Diabled Public Network (124) - SA Blob Public Access (190) - SA Public Access (59) - Queue Logging (33)
          skip_check: CKV_AZURE_160,CKV_AZURE_110,CKV_AZURE_236,CKV_AZURE_170,CKV_AZURE_168,CKV_AZURE_6,CKV_AZURE_124,CKV_AZURE_190,CKV_AZURE_59,CKV_AZURE_33,

  trigger-plan-validation:
    name: Trigger Plan Validation
    runs-on: ubuntu-latest
    needs: checkov-security-analysis

    env:
      ENV: ${{ needs.checkov-security-analysis.outputs.env_name }}

    steps:
      - name: Trigger Terraform Plan Validation Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "terraform-plan-validation.yml",
              ref: context.ref,
            });
