name: Terraform Backend Check

on:
  workflow_dispatch:

jobs:
  backend-check:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-env.outputs.env }}
      tfvars_file: ${{ steps.set-env.outputs.tfvars_file }}
      backend_exists: ${{ steps.set-backend.outputs.backend_exists }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Determine Environment & Backend TFVARS File Based On Branch - Workflow Dispatch
      - name: Determine Branch Environment
        id: set-env
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
                BRANCH="${{ github.base_ref }}"
              else
                BRANCH="${{ github.ref_name }}"
              fi

          case "$BRANCH" in
            dev) ENV="dev" ;;
            staging) ENV="staging" ;;
            main) ENV="production" ;;
            *) echo "Invalid Branch: $BRANCH"; exit 1 ;;
          esac

          TFVARS_FILE="environments/${ENV}/backend.tfvars"

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV

          echo "env=$ENV" >> $GITHUB_OUTPUT
          echo "tfvars_file=$TFVARS_FILE" >> $GITHUB_OUTPUT

          echo "Environment: $ENV"
          echo "Using TFVARS File: $TFVARS_FILE"

      # Clear Cahce
      - name: Clear Cache
        run: |
          echo "Cleaning Cache..."
          rm -rf .terraform .terraform.lock.hcl

          rm -rf environments/${ENV}/.terraform
          rm -f environments/${ENV}/.terraform.lock.hcl

          echo "Cleanup Complete"

        # Azure Authentication
      - name: Azure Login
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # Determine Variables
      - name: Determine Backend Variables
        run: |
          BACKEND_FILE="${TFVARS_FILE}"

          if [ ! -f "$BACKEND_FILE" ]; then
           echo "Backend TFVARS File Not Found: $BACKEND_FILE"
           exit 1
          fi

           RG=$(grep -E '^state_resource_group_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           SA=$(grep -E '^state_storage_account_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           CONTAINER=$(grep -E '^state_storage_container_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           KEY=$(grep -E '^state_key_backend' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)

           RG="${RG//$'\r'/}"
           SA="${SA//$'\r'/}"
           CONTAINER="${CONTAINER//$'\r'/}"
           KEY="${KEY//$'\r'/}"

           echo "RG_NAME=$RG" >> $GITHUB_ENV
           echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
           echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
           echo "STATE_KEY_BACKEND=$KEY" >> $GITHUB_ENV

      - name: Confirming Backend..
        id: set-backend
        shell: bash
        run: |
          echo "Checking Terraform Backend"
          echo "RG        : $RG_NAME"
          echo "Storage   : $STORAGE_ACCOUNT_NAME"
          echo "Container : $STORAGE_CONTAINER_NAME"
          echo "Backend State Key : $STATE_KEY_BACKEND"

          backend_exists=true

          # Resource Group
          echo "Checking Resource Group..."
          if ! az group show \
           --name "$RG_NAME" \
           --output none; then
              echo "Resource Group '$RG_NAME' Missing"
              backend_exists=false
              echo "Skipping Further Checks.."
          else
            echo "Resource Group Exists"

            # Storage Account
            echo "Checking Storage Account..."
            if ! az storage account show \
              --name "$STORAGE_ACCOUNT_NAME" \
              --resource-group "$RG_NAME" \
              --output none; then
                echo "Storage Account Missing"
                backend_exists=false
            fi

            # Container
            echo "Checking Container..."
            if ! az storage container show \
              --name "$STORAGE_CONTAINER_NAME" \
              --account-name "$STORAGE_ACCOUNT_NAME" \
              --auth-mode login \
              --output none; then
                echo "Container Missing"
                backend_exists=false
            fi  

            # State Key
            echo "Checking State Key..."
            set +e
            BLOB_EXISTS=$(az storage blob exists \
              --container-name "$STORAGE_CONTAINER_NAME" \
              --name "$STATE_KEY_BACKEND" \
              --account-name "$STORAGE_ACCOUNT_NAME" \
              --auth-mode login \
              --query exists \
              --output tsv 2>/dev/null)

            if [[ "$BLOB_EXISTS" != "true" ]]; then
              echo "Backend Missing"
              backend_exists=false
            else
              echo "Backend Exists"
            fi
            echo "Backend Exists: $backend_exists"
          fi

           # Set Output For Triggers
          echo "backend_exists=$backend_exists" >> $GITHUB_OUTPUT
          echo "backend_exists=$backend_exists" >> $GITHUB_ENV
          echo "Backend Exists: $backend_exists"

  trigger-infra-deployment:
    name: Trigger Infrastructure Deployment
    runs-on: ubuntu-latest
    needs: backend-check
    if: needs.backend-check.outputs.backend_exists == 'true'

    env:
      ENV: ${{ needs.backend-check.outputs.env_name }}
      TFVARS_FILE: ${{ needs.backend-check.outputs.tfvars_file }}

    steps:
      - name: Deployment Workflow Trigger
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "terraform-infrastructure-deployment.yml",
              ref: context.ref,
            });

  trigger-backend-bootstrap:
    name: Trigger Backend Bootstrap
    runs-on: ubuntu-latest
    needs: backend-check
    if: needs.backend-check.outputs.backend_exists == 'false'

    env:
      ENV: ${{ needs.backend-check.outputs.env_name }}
      TFVARS_FILE: ${{ needs.backend-check.outputs.tfvars_file }}

    steps:
      - name: Trigger Bootstrap Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "terraform-backend-bootstrap.yml",
              ref: context.ref,
            });
