name: Terraform Remote Backend Check

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch To Run Workflow - Leave Empty For Current Branch"
        required: false
        type: string

  pull_request:
    branches:
      - dev
      - staging
      - main
    paths:
      - modules/**
      - environments/dev/**
      - environments/staging/**
      - environments/production/**
      - environments/terraform-backend/**
      - main.tf
      - variables.tf

jobs:
  Remote-Backend-Check:
    runs-on: ubuntu-latest
    env:
      TF_LOG: "ERROR"
      INPUT_BRANCH: ${{ inputs.branch }}
      DISPATCH_BRANCH: ${{ github.event.inputs.branch }}

    outputs:
      env_name: ${{ steps.detect-env.outputs.env }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Determine Branch & Environment
      - name: Determine Branch & Enviroment
        id: detect-env
        shell: bash
        run: |
          echo "Event: $GITHUB_EVENT_NAME"

           if [ "$GITHUB_EVENT_NAME" = "workflow_call" ]; then
            BRANCH="$INPUT_BRANCH"

           elif [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] && [ -n "$DISPATCH_BRANCH" ]; then
            BRANCH="$DISPATCH_BRANCH"

          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            BRANCH="$GITHUB_BASE_REF"

          else
            BRANCH="${GITHUB_REF#refs/heads/}"
          fi

          echo "Branch: $BRANCH"

          case "$BRANCH" in
            dev) ENV="dev" ;;
            staging) ENV="staging" ;;
            main) ENV="production" ;;
            *) echo "Invalid Branch: $BRANCH"; exit 1 ;;
            esac

          TFVARS_FILE="environments/${ENV}/backend.tfvars"

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
          echo "env=$ENV" >> $GITHUB_OUTPUT

          echo "Environment: $ENV"
          echo "Using TFVARS File: $TFVARS_FILE"

        # Terraform Backend Folders & Files
      - name: Terraform Backend Folders & Files
        run: |
          echo "Terraform Backend Folders & Files:"
          for dir in environments/terraform-backend/*; do
            if [ -d "$dir" ]; then
              echo "Folder: $dir"
              ls -1 "$dir"
            fi
          done

      # Determine Backend Variables
      - name: Determine Backend Variables
        run: |
          BACKEND_FILE="${TFVARS_FILE}"

          if [ ! -f "$BACKEND_FILE" ]; then
           echo "Backend TFVARS File Not Found: $BACKEND_FILE"
           exit 1
          fi

           RG=$(grep -E '^state_resource_group_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           SA=$(grep -E '^state_storage_account_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           CONTAINER=$(grep -E '^state_storage_container_name' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)
           KEY=$(grep -E '^state_key_backend' "$BACKEND_FILE" | awk -F'=' '{print $2}' | xargs)

           RG="${RG//$'\r'/}"
           SA="${SA//$'\r'/}"
           CONTAINER="${CONTAINER//$'\r'/}"
           KEY="${KEY//$'\r'/}"

           echo "RG_NAME=$RG" >> $GITHUB_ENV
           echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
           echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
           echo "STATE_KEY_BACKEND=$KEY" >> $GITHUB_ENV

        # Azure Authentication
      - name: Azure Login
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # Check Azure Remote Backend
      - name: Confirming Backend..
        id: set-backend
        shell: bash
        run: |
          echo "Checking Terraform Backend"
          echo "RG        : $RG_NAME"
          echo "Storage   : $STORAGE_ACCOUNT_NAME"
          echo "Container : $STORAGE_CONTAINER_NAME"
          echo "Backend State Key : $STATE_KEY_BACKEND"

          backend_exists=true

          # Resource Group
          echo "Checking Resource Group..."
          if ! az group show \
           --name "$RG_NAME" \
           --output none; then
              echo "Resource Group '$RG_NAME' Missing"
              exit 1
              echo "Skipping Further Checks.."
          else
            echo "Resource Group Exists"

            # Storage Account
            echo "Checking Storage Account..."
            if ! az storage account show \
              --name "$STORAGE_ACCOUNT_NAME" \
              --resource-group "$RG_NAME" \
              --output none; then
                echo "Storage Account Missing"
                exit 1
            else
              echo "Storage Account Exists"
            fi

            # Container
            echo "Checking Container..."
            if ! az storage container show \
              --name "$STORAGE_CONTAINER_NAME" \
              --account-name "$STORAGE_ACCOUNT_NAME" \
              --auth-mode login \
              --output none; then
                echo "Container Missing"
                exit 1
              else
                echo "Container Exists"
            fi  

            # State Key
            echo "Checking State Key..."
            set +e
            BLOB_EXISTS=$(az storage blob exists \
              --container-name "$STORAGE_CONTAINER_NAME" \
              --name "$STATE_KEY_BACKEND" \
              --account-name "$STORAGE_ACCOUNT_NAME" \
              --auth-mode login \
              --query exists \
              --output tsv 2>/dev/null)

            if [[ "$BLOB_EXISTS" != "true" ]]; then
              echo "State Key Missing"
              exit 1
            else
              echo "Backend Exists"
            fi

           # Backend Exists If Reached This Step
           echo "backend_exists=true" >> $GITHUB_OUTPUT
           echo "backend_exists=true" >> $GITHUB_ENV
           echo "Backend Exists: true"
